### ISSUE TITLE
Extension host crashing when editing Elm files

### ISSUE THREAD

**Issue by derrickreimer** [Krzysztof-Cieslak/vscode-elm#276]
- Extension Name: elm
- Extension Version: 0.22.0
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.0

## Behavior

This just started happening after upgrading to the latest VSCode version. When working with Elm files, the Extension Host repeatedly stops responding and is pegged at 100% CPU.

The Process Explorer:

![image](https://user-images.githubusercontent.com/341387/46691541-ce504700-cbca-11e8-8a0b-7a9cc17d3a60.png)

The UI message:

![image](https://user-images.githubusercontent.com/341387/46691612-ecb64280-cbca-11e8-9e3e-149b8040dc74.png)

I narrowed it down to the Elm extension by process of elimination:

- Disabled all extensions and re-enabled + restarted one-by-one
- Observed the behavior consistently when enabling the Elm extension and after opening/interacting with a .elm file

Please let me know if there's anything else I can provide to help troubleshoot.

**Comment by derrickreimer** [comment]
Here's an error message I found in the Developer Tools console:

```
ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at ElmCodeActionProvider.provideCodeActions (/Users/derrickreimer/.vscode/extensions/sbrink.elm-0.22.0/out/src/elmCodeAction.js:6:54)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:501:615
	at t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:368)
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:776)
	at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:333)
	at e.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:501:574)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:516:103
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:512:91)
	at e.$provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:516:65)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:888)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:554)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:639:60)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:638:59)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:926
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:138
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:213)
	at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

Not sure if it's relevant.

**Comment by derrickreimer** [comment]
Once more piece of information!

I can cause the extension host to crash by:

- Opening an elm file
- Mouse hovering over a function definition
  - The fly-out shows `Loading...` and just hangs
- About 5 seconds later, the "Extension Host is unresponsive" dialog appears and CPU pegs

I disabled the hover globally and the crashing has stopped:

```
"editor.hover.enabled": false
```

**Comment by hakonrossebo** [comment]
I can't see anything in the elmCodeAction.ts file that can cause this. Could this be related to a vscode performance issue? https://github.com/Microsoft/vscode/issues/60465

**Comment by mjarkk** [comment]
I found that one of my extensions was taking really long to load (more than 10s) because vscode didn't get a response from the extension within 10s it seems to kill all extension and start using way to much CPU usage and start doing wired things.
Take a look at the bottom of the screen when vscode loads and see if there are any extensions that take more then 10 seconds

![image](https://user-images.githubusercontent.com/15320763/46749222-8c4fff80-ccb5-11e8-99d4-49d07e995420.png)

**Comment by derrickreimer** [comment]
The UI makes no indication of extensions taking a long time to load. The extension profiler also does not indicate any extensions are blocking.

**Comment by gpickin** [comment]
Not sure if it helps or not, but I am getting crashes on other extensions ( I don’t have this one but a properties file extension ) in a similar fashion. Will compare

**Comment by Krzysztof-Cieslak** [comment]
Can anyone confirm this is really caused by our extension? I.e. try reproducing the problem with all other extensions disabled.

**Comment by mjarkk** [comment]
Not that i know something about this extensions  
but you can try to remake my problem from another extension: https://github.com/ExodiusStudios/vscode-comment-anchors/issues/18  

Steps:
- Create a work space with multiple folder
- Have at least a lot of files something around 100.000 (that's around the amount of files in have in my work space probably 95% of the files are inside node_modules)
- Open the work space and see if it vscode starts behaving wired

Notes: 
- The extension i used scan's every file as far as i know (it might be handy to only create elm files if you follow the steps)
- The extension i used doesn't scan node_modules

**Comment by hakonrossebo** [comment]
I've tried to reproduce this on Windows and Linux on different projects (also elm-spa-example) without success - no issues on my machine. Is there any open source projects i can clone and reproduce this with?

**Comment by mjarkk** [comment]
You can try some of these: https://github.com/trending/elm ,just clone some and put them in a work space together
