### ISSUE TITLE
Extension v0.24 fails to load with ES range syntax error / MacOS X

### ISSUE THREAD

**Issue by shamansir** [Krzysztof-Cieslak/vscode-elm#297]
Extension v0.24 fails to load in my case:

* Elm v0.18
* Mac OS X
* VSCode Version 1.23.1

The quote from #289:

I've managed to find the source of the error and it seems to be different from what was discussed here, since it can be caused by `elm-module-parser`:

```
[Extension Host] Activating extension `sbrink.elm` failed:  Unexpected token ...
[Extension Host] Here is the error stack:  /Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/parsers/elm_module_parser.js:232
/private/var/folders/vf/6_v784pj3mg3ryt3rc5f71_c0000gn/T/AppTranslocation/A…dio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Here is the error stack:  /Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/parsers/elm_module_parser.js:232
              ...name,
              ^^^
SyntaxError: Unexpected token ...
	at createScript (vm.js:53:10)
	at Object.runInThisContext (vm.js:95:10)
	at Module._compile (module.js:543:28)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/private/var/folders/vf/6_v784pj3mg3ryt3rc5f71_c0000gn/T/AppTranslocation/A29C9F8E-3C58-4F2A-9699-09F6FBC88B00/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/private/var/folders/vf/6_v784pj3mg3ryt3rc5f71_c0000gn/T/AppTranslocation/A29C9F8E-3C58-4F2A-9699-09F6FBC88B00/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.loadParser (/Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/src/util.js:11:19)
	at Object.<anonymous> (/Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/src/module_parser.js:4:32)
	at Object.<anonymous> (/Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/src/module_parser.js:36:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
...
```

The minified source in my case contains these lines in `workbench.main.js`:

```js
                getDuration: function(e, t) {
                    const n = global._performanceEntries;
                    let i = e
                      , r = 0;
                    for (let o = 0; o < n.length; o += 4)
                        if (n[o + 1] === i) {
                            if (i !== e)
                                return n[o + 2] - r;
                            i = t,
                            r = n[o + 2]
                        }
                    return 0
                },
                importEntries: function(e) {
                    global._performanceEntries.splice(0, 0, ...e) // <-- could be the source of the error
                },
                exportEntries: function() {
                    return global._performanceEntries.slice(0)
                }
```

**Comment by joeandaverde** [comment]
I'll fix this.

**Comment by joeandaverde** [comment]
I've fixed this in elm-module-parser. However, I'm curious what version of node is running in your VSCode process?
